customhost   =  "database-1.cgyckgniwvyw.ap-south-1.rds.amazonaws.com"
customuser   = "root"
custompass   = "root1234"
customdb     = "project"
custombucket = "emp-info-bucket"
customregion = "ap-south-1"