---
- name: Install Minikube and set up cluster
  hosts: ec2
  gather_facts: true
  become: true

  tasks:
    - name: Install dependencies
      apt:
        name:
          - docker.io
          - curl
        state: present

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Install kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Download and install Minikube
      shell: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube

    - name: Start Minikube cluster
      shell: minikube start --driver=docker

    - name: Configure kubectl
      shell: minikube kubectl -- get pods --all-namespaces

    - name: Enable Kubernetes addons
      shell: minikube addons enable ingress

    - name: Display cluster information
      shell: minikube status
