apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp-container
          image: 126681421555.dkr.ecr.ap-south-1.amazonaws.com/web-app-repository-week-assignment:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred