apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - name: tcp
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080